// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfvlpjpiotjylfbnmglb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmdmxwanBpb3RqeWxmYm5tZ2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDg0MDIsImV4cCI6MjA3MDEyNDQwMn0.9cOO8wq_mNSFfkfMOOxB5N2yNTeGSHa4DjGs9IygWQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});